"""MOAT layer 2 unit tests — calibration, absolute pressure units, 3-D, potential.

These validate the physics that turns the relative pixel heatmap into an ABSOLUTE
1/s^2 early-warning alarm. Runnable two ways:

    pytest tests/test_moat2.py            # if pytest is installed
    PYTHONPATH=. python tests/test_moat2.py   # plain-python fallback runner
"""
from __future__ import annotations

import numpy as np

from flowsight.geometry.calibration import (
    HomographyCalibrator,
    PedestrianScaleCalibrator,
)
from flowsight.geometry.camera import PinholeCamera
from flowsight.geometry.terrain import Terrain, ramp_basin_elevation
from flowsight.physics import potential
from flowsight.physics.crowd_pressure import (
    P_CRIT,
    alarm_level,
    frame_pressure_metric,
)
from flowsight.pipeline.moat_field import (
    MoatMonitor,
    build_dem_from_points,
    foot_points_to_world,
)


# --------------------------------------------------------------------------- #
# 1. Calibration
# --------------------------------------------------------------------------- #
def test_pedestrian_scale_from_heights():
    cal = PedestrianScaleCalibrator.from_bbox_heights([80, 85, 90])  # median 85
    assert abs(cal.s - 1.7 / 85.0) < 1e-9
    # 50 px -> 1.0 m at this scale
    g = cal.to_ground([[50.0, 0.0]])[0]
    assert abs(g[0] - 50.0 * cal.s) < 1e-9
    v = cal.velocity_to_metric([[50, 0]], [[10.0, 0.0]])[0]
    assert abs(v[0] - 10.0 * cal.s) < 1e-9


def test_homography_position_and_velocity_roundtrip():
    """Crowd defined in METRES, projected to pixels, calibrated back -> recovered.

    Velocity in pixels is generated by finite differences through the inverse
    homography, so this also checks the analytic Jacobian against ground truth.
    """
    rng = np.random.default_rng(0)
    # image corners -> a perspective-distorted ground quad (metres)
    img = [[0, 0], [640, 0], [640, 480], [0, 480]]
    wld = [[0, 0], [12, 0], [10, 9], [1, 8]]
    cal = HomographyCalibrator.from_points(img, wld)
    Hinv = np.linalg.inv(cal.H)

    def ground_to_img(xy):
        xy = np.atleast_2d(xy)
        hom = np.hstack([xy, np.ones((len(xy), 1))]) @ Hinv.T
        return hom[:, :2] / hom[:, 2:3]

    xy_m = rng.uniform([1, 1], [9, 7], size=(40, 2))
    vel_m = rng.normal(0, 0.8, size=(40, 2))
    dt = 1e-3
    uv0 = ground_to_img(xy_m)
    uv1 = ground_to_img(xy_m + vel_m * dt)
    vel_px = (uv1 - uv0) / dt

    rec_xy = cal.to_ground(uv0)
    rec_vel = cal.velocity_to_metric(uv0, vel_px)
    assert np.abs(rec_xy - xy_m).max() < 1e-6
    assert np.abs(rec_vel - vel_m).max() < 1e-3  # finite-diff vs analytic Jacobian


# --------------------------------------------------------------------------- #
# 2. Absolute pressure UNITS — the crux of the moat
# --------------------------------------------------------------------------- #
def test_absolute_pressure_units():
    """Uniform crowd of known density & velocity variance -> P = rho*Var in 1/s^2.

    rho = 4 persons/m^2 ; per-axis vel var 0.09 -> Var(v) = 0.18 (m/s)^2
    => expected P ~ 0.72 /s^2 (well above the 0.02 Helbing threshold).
    """
    rng = np.random.default_rng(3)
    L = 20.0
    rho_target = 4.0
    N = int(rho_target * L * L)  # 1600
    xy = rng.uniform(0, L, size=(N, 2))
    vel = rng.normal(0, 0.3, size=(N, 2))  # per-axis var 0.09
    fld = frame_pressure_metric(xy, vel, (0, 0, L, L), cell_m=0.5, sigma_m=1.0)

    # interior cells only (avoid constant-mode smoothing fall-off at edges)
    gh, gw = fld["pressure"].shape
    sl = (slice(gh // 4, 3 * gh // 4), slice(gw // 4, 3 * gw // 4))
    rho_med = float(np.median(fld["density"][sl]))
    var_med = float(np.median(fld["var_v"][sl]))
    p_med = float(np.median(fld["pressure"][sl]))

    assert abs(rho_med - 4.0) < 0.8, rho_med            # persons/m^2
    assert abs(var_med - 0.18) < 0.06, var_med          # (m/s)^2
    assert abs(p_med - 0.72) < 0.25, p_med              # 1/s^2
    # P == rho*Var elementwise (definition holds)
    assert np.allclose(fld["pressure"], fld["density"] * fld["var_v"], atol=1e-6)


def test_alarm_thresholds():
    assert alarm_level(0.005)["severity"] == "safe"
    assert alarm_level(0.010)["severity"] == "caution"  # boundary 0.5*crit
    assert alarm_level(0.015)["severity"] == "caution"
    assert alarm_level(0.020)["severity"] == "danger"   # boundary crit
    assert alarm_level(0.050)["severity"] == "danger"
    assert abs(alarm_level(0.04)["frac"] - 2.0) < 1e-9  # 0.04 / 0.02


# --------------------------------------------------------------------------- #
# 3. Non-planar 3-D: backprojection + DEM
# --------------------------------------------------------------------------- #
def test_backproject_and_dem_recovery():
    terr = Terrain(elevation_fn=ramp_basin_elevation())
    cam = PinholeCamera.look_at(
        C=(0, -10, 12), target=(0, 30, -5), f=600, width=640, height=480
    )
    xs = np.linspace(-4, 4, 5)
    ys = np.linspace(5, 34, 6)
    WX, WY = np.meshgrid(xs, ys)
    WZ = terr.elevation(WX, WY)
    P = np.column_stack([WX.ravel(), WY.ravel(), WZ.ravel()])
    uv, depthZ = cam.project(P)

    # dense-equivalent: sample exact uv with true camera-Z -> exact world
    dm = np.zeros((480, 640))
    iu = np.clip(uv[:, 0].astype(int), 0, 639)
    iv = np.clip(uv[:, 1].astype(int), 0, 479)
    dm[iv, iu] = depthZ
    rec = foot_points_to_world(cam, np.column_stack([iu, iv]).astype(float), dm)
    ref = cam.backproject_depth(np.column_stack([iu, iv]).astype(float), depthZ)
    assert np.abs(rec - ref).max() < 1e-6

    # DEM recovers terrain elevation at the sampled points
    terr2 = build_dem_from_points(P, (-6, 3, 6, 36), cell=0.5)
    samp = terr2.elevation(WX.ravel(), WY.ravel())
    assert np.abs(samp - WZ.ravel()).mean() < 0.05


# --------------------------------------------------------------------------- #
# 4. Gravitational potential: downhill force direction & magnitude
# --------------------------------------------------------------------------- #
def test_potential_downhill_force():
    # ramp: z = -tan(theta)*(y - y0) for y>y0 -> slopes DOWN toward +y
    theta = np.deg2rad(20.0)
    terr = Terrain(elevation_fn=ramp_basin_elevation(y0=10.0, theta_deg=20.0,
                                                     basin_y=999, basin_depth=0))
    x = np.array([0.0, 0.0])
    y = np.array([20.0, 25.0])  # on the ramp
    Fx, Fy, Fmag = potential.potential_gradient(terr, x, y)
    assert np.all(Fy > 0)                       # force points downhill (+y)
    assert np.all(np.abs(Fx) < 1e-6)            # no cross-slope component
    expected = potential.MASS * potential.G * np.tan(theta)
    assert np.all(np.abs(Fmag - expected) < 0.5 * expected)  # ~ m g tan(theta)


def test_moat_monitor_terrain_channel_active_on_slope():
    terr = Terrain(elevation_fn=ramp_basin_elevation())
    bounds = (-6, 3, 6, 36)
    rng = np.random.default_rng(1)
    N = 300
    xy = np.column_stack([rng.uniform(-3, 3, N), rng.uniform(28, 34, N)])
    vel = rng.normal(0, 0.3, size=(N, 2))
    mon = MoatMonitor(bounds, terrain=terr, cell_m=0.5, sigma_m=1.0)
    r = mon.step_metric(xy, vel)
    assert r["p_max"] > P_CRIT                 # dense erratic crowd -> danger
    assert r["alarm"]["severity"] == "danger"
    assert r["terrain_push_max"] > 0           # non-planar channel is active
    assert r["Fmag"].max() > 0


# --------------------------------------------------------------------------- #
# plain-python fallback runner (no pytest needed)
# --------------------------------------------------------------------------- #
if __name__ == "__main__":
    fns = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    passed = 0
    for fn in fns:
        try:
            fn()
            print("PASS", fn.__name__)
            passed += 1
        except Exception as e:  # noqa: BLE001
            print("FAIL", fn.__name__, "->", repr(e))
    print("\n%d/%d passed" % (passed, len(fns)))
    raise SystemExit(0 if passed == len(fns) else 1)
